name: todo_flutter
description: "Simple todo app with riverpod"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flex_color_scheme: ^8.1.0
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  go_router: ^14.7.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  path: ^1.9.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
